import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 50;
const BRAND = rgb(0.267, 0.220, 0.788);
const INK = rgb(0.06, 0.09, 0.16);
const MUTED = rgb(0.42, 0.45, 0.5);

function money(price) {
  if (!price?.min) return "Price on Request";
  return `Rs. ${Number(price.min).toLocaleString("en-IN")}${price.max && price.max !== price.min ? ` - Rs. ${Number(price.max).toLocaleString("en-IN")}` : ""}`;
}

/**
 * Auto-generates a PDF product catalog straight from the vendor's live
 * product listings — no manual upload needed. This is the same "always
 * up to date" catalog concept IndiaMART/TradeIndia sellers get.
 */
export async function generateCatalogPdf(vendor, products, appName) {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  const text = (str, x, yy, opts = {}) => {
    page.drawText(String(str ?? ""), { x, y: yy, size: opts.size || 10, font: opts.bold ? bold : font, color: opts.color || INK });
  };

  const newPage = () => {
    page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;
  };

  // Cover
  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 200, width: PAGE_WIDTH, height: 200, color: BRAND });
  text(vendor.businessName, MARGIN, PAGE_HEIGHT - 90, { size: 24, bold: true, color: rgb(1, 1, 1) });
  text("Product Catalog", MARGIN, PAGE_HEIGHT - 120, { size: 14, color: rgb(0.9, 0.9, 1) });
  text(`Generated by ${appName}`, MARGIN, PAGE_HEIGHT - 180, { size: 9, color: rgb(0.85, 0.85, 1) });

  y = PAGE_HEIGHT - 230;
  text([vendor.city, vendor.state].filter(Boolean).join(", "), MARGIN, y, { size: 10, color: MUTED });
  y -= 16;
  if (vendor.phone) {
    text(`Phone: ${vendor.phone}`, MARGIN, y, { size: 10, color: MUTED });
    y -= 16;
  }
  if (vendor.email) {
    text(`Email: ${vendor.email}`, MARGIN, y, { size: 10, color: MUTED });
    y -= 16;
  }
  if (vendor.description) {
    text(vendor.description.slice(0, 200), MARGIN, y, { size: 9, color: MUTED });
    y -= 30;
  }

  y -= 20;
  text(`${products.length} Products`, MARGIN, y, { size: 12, bold: true });
  y -= 30;

  for (const p of products) {
    if (y < 120) newPage();

    page.drawRectangle({ x: MARGIN, y: y - 66, width: PAGE_WIDTH - MARGIN * 2, height: 78, borderColor: rgb(0.9, 0.9, 0.93), borderWidth: 1 });
    text(p.name, MARGIN + 12, y - 16, { size: 11, bold: true });
    text(money(p.price), MARGIN + 12, y - 34, { size: 10, color: BRAND, bold: true });
    text(`MOQ: ${p.moq || 1} ${p.moqUnit || "piece"}`, MARGIN + 12, y - 50, { size: 8, color: MUTED });
    if (p.description) {
      text(p.description.slice(0, 110), MARGIN + 220, y - 34, { size: 8, color: MUTED });
    }
    y -= 90;
  }

  text(`${vendor.businessName} — auto-generated catalog. Prices subject to change.`, MARGIN, 30, { size: 7, color: MUTED });

  return doc.save();
}
